/**
 * PDF UI strings keyed by ISO 639-1.
 * Non-Latin locales (e.g. ja) fall back to English — jsPDF Helvetica is WinAnsi-only.
 */
const LABELS = {
  id: {
    title: 'Split Complete',
    totalPaid: 'Total dibayar',
    items: 'ITEM',
    noItems: 'Tidak ada item',
    feeSummary: 'RINGKASAN BIAYA',
    personTotal: (name) => `Total ${name}`,
    subtotal: 'Subtotal',
    discount: 'Diskon',
    taxAndService: 'Pajak & Service Charge',
    sharedCost: 'Biaya bersama',
    otherFees: 'Biaya lain',
    generatedBy: (appName) => `Dibuat oleh ${appName}`,
  },
  en: {
    title: 'Split Complete',
    totalPaid: 'Total paid',
    items: 'ITEMS',
    noItems: 'No items',
    feeSummary: 'FEE SUMMARY',
    personTotal: (name) => `Total ${name}`,
    subtotal: 'Subtotal',
    discount: 'Discount',
    taxAndService: 'Tax & Service Charge',
    sharedCost: 'Shared cost',
    otherFees: 'Other fees',
    generatedBy: (appName) => `Generated by ${appName}`,
  },
};

export function getPdfLabels(languageCode) {
  const code = String(languageCode || 'en')
    .trim()
    .toLowerCase()
    .slice(0, 2);
  return LABELS[code] || LABELS.en;
}
