services:
  splitbill-frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-https://splitbill.inviteweeding.my.id/api/v2}
    image: splitbill-frontend:latest
    ports:
      - "${PORT:-8082}:80"
    restart: unless-stopped
